CREATE TABLE dinner_users (
    userid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    token TEXT NOT NULL,
    meal_index INTEGER NOT NULL,
    short_index INTEGER NOT NULL,
    medium_index INTEGER NOT NULL,
    long_index INTEGER NOT NULL
);