CREATE TABLE dinner_meals (
    mealid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    userid TEXT NOT NULL,
    rotation TEXT NOT NULL,
    FOREIGN KEY (userid) REFERENCES dinner_users (userid),
    date_last_eaten TIMESTAMP DEFAULT now() NOT NULL
);