CREATE TABLE dinner_meals (
    mealid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    meal TEXT NOT NULL,
    rotation TEXT NOT NULL,
    userid INTEGER REFERENCES dinner_users(userid) NOT NULL,
    date_last_eaten TIMESTAMP NOT NULL
);