INSERT INTO dinner_meals (name, userid, rotation)
VALUES
  ('Curry', 'Kris', 'short' ),
  ('Chili', 'Kris', 'short' ),
  ('Salad', 'Kris', 'short' ),
  ('Steak', 'Kris', 'short' ),
  ('Yakisoba', 'Kris', 'medium' ),
  ('Ramen', 'Kris', 'medium' ),
  ('Sushi', 'Kris', 'medium' ),
  ('Meatloaf', 'Kris', 'medium' ),
  ('Burger', 'Kris', 'long' ),
  ('Pancakes', 'Kris', 'long' ),
  ('Fried Rice', 'Kris', 'long' ),
  ('Eggplant Parmesan', 'Kris', 'long' ),
  ('Curry', 'Alex', 'short' ),
  ('Chili', 'Alex', 'short' ),
  ('Salad', 'Alex', 'short' ),
  ('Steak', 'Alex', 'short' ),
  ('Yakisoba', 'Alex', 'medium' ),
  ('Ramen', 'Alex', 'medium' ),
  ('Sushi', 'Alex', 'medium' ),
  ('Meatloaf', 'Alex', 'medium' ),
  ('Burger', 'Alex', 'long' ),
  ('Pancakes', 'Alex', 'long' ),
  ('Fried Rice', 'Alex', 'long' ),
  ('Eggplant Parmesan', 'Alex', 'long' ),
  ('Curry', 'Andy', 'short' ),
  ('Chili', 'Andy', 'short' ),
  ('Salad', 'Andy', 'short' ),
  ('Steak', 'Andy', 'short' ),
  ('Yakisoba', 'Andy', 'medium' ),
  ('Ramen', 'Andy', 'medium' ),
  ('Sushi', 'Andy', 'medium' ),
  ('Meatloaf', 'Andy', 'medium' ),
  ('Burger', 'Andy', 'long' ),
  ('Pancakes', 'Andy', 'long' ),
  ('Fried Rice', 'Andy', 'long' ),
  ('Eggplant Parmesan', 'Andy', 'long' );
